# Generated by Django 4.1 on 2022-12-27 17:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalIndicador',
            new_name='HistoricalIndicator',
        ),
        migrations.RenameModel(
            old_name='Indicador',
            new_name='Indicator',
        ),
    ]
