# Generated by Django 4.1 on 2022-12-29 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_categoryproduct_measure_unit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryproduct',
            options={'verbose_name': 'Categoria de producto', 'verbose_name_plural': 'Categorias de productos'},
        ),
        migrations.AlterModelOptions(
            name='historicalcategoryproduct',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Categoria de producto', 'verbose_name_plural': 'historical Categorias de productos'},
        ),
    ]
